---
  'copernicus_marine':
    'username': 'EXAMPLE@gmail.com'
    'password': 'EXAMPLE_PASSWORD'
    'nc_files_path': '/path/to/along-track-data'
    'eddies_file_path': '/path/to/Data/eddy'
  'db_connect':
    'host': 'postgres'
    'username': 'postgres'
    'password': 'postgres'
    'port': 5432