networks:
  ocean_network:
    name: ocean_network
    external: true

services:
  postgres:
    image: postgis/postgis:16-3.4
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ocean_db
    networks:
      - ocean_network
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: oceandb_postgres_data

