networks:
  ocean_network:
    name: ocean_network
    external: true


services:
  ocean_db_client:
    image: ocean_db_client:latest
    stdin_open: true
    tty: true
    volumes:
      - ./OceanDB:/app/OceanDB
      - ./data:/app/data
#      - ./data/copernicus:/app/data
#      - ./data/cop
      - .env:/app/.env
    networks:
      - ocean_network
